<div class="owl-slider">
	<div id="carousel" class="owl-carousel">
		<div class="item">
			<img class="images" src="<?php echo $block->getViewFileUrl('images/banner-grid.jpg'); ?>" />
		</div>
		<div class="item">
			<img class="images" src="<?php echo $block->getViewFileUrl('images/banner-grid.jpg'); ?>" />
		</div>
		<div class="item">
			<img class="images" src="<?php echo $block->getViewFileUrl('images/banner-grid.jpg'); ?>" />
		</div>
	</div>
</div>
<script>

	require(['jquery','owl'], function ($) {


		jQuery("#carousel").owlCarousel({
			autoplay: true,
			lazyLoad: true,
			loop: true,
			margin: 20,
   /*
  animateOut: 'fadeOut',
  animateIn: 'fadeIn',
  */
  responsiveClass: true,
  autoHeight: true,
  autoplayTimeout: 7000,
  smartSpeed: 800,
  nav: false,
  responsive: {
  	0: {
  		items: 1
  	},

  	600: {
  		items: 1
  	},

  	1024: {
  		items: 1
  	},

  	1366: {
  		items: 1
  	}
  }
});

	});
</script>