<?php
$_product = $block->getProduct(); // GET THE PRODUCT
?>
<ul>
	<li>SHARE:</li>
	<li><a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on FaceBook"><i class="fab fa-facebook-f"></i></a></li>
	
	<li><a href="http://twitter.com/home/?status=<?php echo urlencode($_product->getProductUrl());?>(<?php echo urlencode($_product->getName())?>)" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on Twitter"><i class="fab fa-twitter"></i></a></li>
	<li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
	<li><a href="#"><i class="fab fa-pinterest-square"></i></a></li>
	<li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
	<li><a href="#"><i class="fab fa-youtube"></i></a></li>
</ul>