<div class="sidebar">
	<div class="title">
		<h3>BESTSELLERS</h3>
	</div>
	<div class="wrapper">
		<div class="item">
			<div class="images"><img class="images" src="<?php echo $block->getViewFileUrl('images/sibar1.jpg'); ?>" /></div>
			<div class="content">
				<p class="product-name">Leather Belt</p>
				<p class="old-price">$199.00</p>
				
			</div>
			
		</div>
		<hr>
		<div class="item">
			<div class="images"><img class="images" src="<?php echo $block->getViewFileUrl('images/sibar2.jpg'); ?>" /></div>
			<div class="content">
				<p class="product-name">Sequin Summer Suit</p>
				<p class="old-prices">$250.00</p>
				<p class="special-price">$189.00</p>

			</div>
			
		</div>
		<hr>
		<div class="item">
			<div class="images"><img class="images" src="<?php echo $block->getViewFileUrl('images/sibar3.jpg'); ?>" /></div>
			<div class="content">
				<p class="product-name">Classic Shoes</p>
				<p class="old-price">$612.00</p>
				
			</div>
		</div>
		<hr>

	</div>
</div>
<div class="tags">
	<h3>TAGS</h3>
	<div class="wrapper">
		<div class="item">
			<p>Handbag</p>
			<p>Leather</p>
			<p>Vintage</p>
		</div>
		<div class="item">
			<p>Women</p>
			<p>Sexy Dress</p>
			<p>Shopping</p>
		</div>
	</div>
</div>