<div class="footer-custom">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<img class="images" src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" />
				<p>ADD: <span>Walls Street 68,Mahattan,New York,USA</span></p>
				<p>PHONE: <span>(+84)973378001</span></p>
				<p>EMAIL: <span>info@trendtheme.com</span></p>
				
			</div>
			<div class="col-md-3">
				<h3>POPULAR TAGS</h3>
				<p><span class="hash-tag">New In</span><span class="hash-tag">Men's</span><span class="hash-tag">Glasses</span></p>
				<p><span class="hash-tag">Best Sellers</span><span class="hash-tag">Top Brands</span></p>
				<p><span class="hash-tag">Sale & Special Offers</span></p>
				<p><span class="hash-tag">LookBook</span><span class="hash-tag">Top View</span></p>
				<p><span class="hash-tag">View all</span></p>
				
			</div>
			<div class="col-md-3">
				<div class="content">
					<div class="images"><i class="fad fa-paper-plane"></i></div>
					<div class="contents">
						<h3>FREE SHIPPING WORLDWIDE</h3>
						<p>On Oder over $200</p>
					</div>
				</div>
				<div class="content">
					<div class="images"><i class="fad fa-paper-plane"></i></div>
					<div class="contents">
						<h3>FREE SHIPPING WORLDWIDE</h3>
						<p>On Oder over $200</p>
					</div>
				</div>
				<div class="content">
					<div class="images"><i class="fad fa-paper-plane"></i></div>
					<div class="contents">
						<h3>FREE SHIPPING WORLDWIDE</h3>
						<p>On Oder over $200</p>
						<a href=""><i class="fab fa-google-plus-g"></i></a>	
					</div>
				</div>
				
			</div>
			<div class="col-md-3">
				<h3>FOLLOW US ON</h3>
				<ul class="social">
					<li></li>
					<li></li>
					<li></li>
					<li></li>
					<li></li>
				</ul>
				
				
			</div>
			
		</div>

	</div>
</div>