<div class="content">
	<div class="images"><i class="far fa-paper-plane"></i></div>
	<div class="contents">
		<h3>FREE SHIPPING WORLDWIDE</h3>
		<p>On Oder over $200</p>
	</div>
</div>
<div class="content">
	<div class="images"><i class="fas fa-calendar-plus"></i></div>
	
	<div class="contents">
		<h3>FREE SHIPPING WORLDWIDE</h3>
		<p>On Oder over $200</p>
	</div>
</div>
<div class="content">
	<div class="images"><i class="fas fa-shield-alt"></i></div>
	<div class="contents">
		<h3>FREE SHIPPING WORLDWIDE</h3>
		<p>On Oder over $200</p>
		
	</div>
</div>