<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>

<?php
$type = 'widget-product-grid';

$mode = 'grid';

$image = 'new_products_content_widget_grid';
$items = $block->getProductCollection()->getItems();

$showWishlist = true;
$showCompare = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$description = false;
?>





<div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">

    <?php if ($block->getTitle()) : ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
    <?php endif ?>
    <div class="block-content">
        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
            <ol class="product-items <?= /* @noEscape */ $type ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item) : ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>

                        
                    </script>
                    <div class="product-item-details">
                   <?php if($block->getProductCollection()->getSize()==1) :?>

                   <p style="color: red">TODAY'S HOT DEAL</p>

                   <?php endif ;?>
                   <strong class="product-item-name">
                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                       class="product-item-link">
                       <?= $block->escapeHtml($_item->getName()) ?>
                   </a>

               </strong>


               <?php if($block->getProductCollection()->getSize()==1) :?>


               <p class="special_from_date" style="display: none;"><?= $_item['special_from_date'] ?></p>
               <p class="special_to_date" style="display: none;"><?= $_item['special_to_date']?></p>
               <div class="short-description"><?= $_item['short_description'] ?></div>
               <div id="timer" class="timer">
                  <div id="days" class="style-one"></div>
                  <div id="hours" class="style-one"></div>
                  <div id="minutes" class="style-one"></div>
                  <div id="seconds" class="style-one"></div>
              </div>





          <?php  endif ; ?>

          <?php if ($templateType) : ?>
            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
        <?php endif; ?>

        <?= $block->getProductPriceHtml($_item, $type) ?>

        <?= $block->getProductDetailsHtml($_item) ?>

        <?php if ($showWishlist || $showCompare || $showCart) : ?>
            <div class="product-item-inner">
                <div class="product-item-actions">
                    <?php if ($showCart) : ?>
                        <div class="actions-primary">
                            <?php if ($_item->isSaleable()) : ?>
                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                    <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                    class="action tocart primary">
                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                </button>
                            </form>
                            <?php else : ?>
                                <?php if ($_item->getIsSalable()) : ?>
                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else : ?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($showWishlist || $showCompare) : ?>
                            <div class="actions-secondary" data-role="add-to-links">
                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                <a href="#"
                                data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                            <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                            <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
</div>
<?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
<?php endforeach ?>
</ol>
</div>
<?= $block->getPagerHtml() ?>
</div>
</div>
<?php endif;?>
<script>
    require(['jquery'],function($){


       function makeTimer() {

    //      var endTime = new Date("29 April 2018 9:56:00 GMT+01:00");  
    var endTime = new Date($('.special_to_date').text());          
    endTime = (Date.parse(endTime) / 1000);

    var now = new Date();
    now = (Date.parse(now) / 1000);

    var timeLeft = endTime - now;

    var days = Math.floor(timeLeft / 86400); 
    var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
    var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
    var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));

    if (hours < "10") { hours = "0" + hours; }
    if (minutes < "10") { minutes = "0" + minutes; }
    if (seconds < "10") { seconds = "0" + seconds; }

    $("#days").html("<span>DAYS</span>"+"<span>"+days+"</span>");
    $("#hours").html("<span>HOURS</span>"+"<span>"+hours+"</span>");
    $("#minutes").html("<span>MINS</span>"+"<span>"+minutes+"</span>");
    $("#seconds").html("<span>SECS</span>"+"<span>"+seconds+"</span>");       

}

setInterval(function() { makeTimer(); }, 1000);


});
</script>