<div class="blog-list container">
	
		<div class="row-s">
			<div class="col-md-12">
				<div class="main-contents">
					<div class="content-seller"><h3>BLOG</h3></div>
					<div class="move-center">
						<img class="images left" src="<?php echo $block->getViewFileUrl('images/left.png'); ?>" />
						<span>POSTS</span>
						<img class="images right" src="<?php echo $block->getViewFileUrl('images/right.png'); ?>" />
					</div>
				</div>
				<div class="tab-ngang">
					<div class="tab-ngang-1"></div>
					<div class="tab-ngang-1"></div>
				</div>
				<div id="owl-demo" class="owl-carousel owl-theme owl-theme-blog">
					<div class="item">
						
						<div class="images-blog"><img class="images-blogs" src="<?php echo $block->getViewFileUrl('images/blog1.jpg'); ?>" /></div>
						<div class="content">
							<div class="title">Lorem Ipsum is simply dummy text of the printing.</div>
							<div class="contents">Lorem Ipsum is simply dummy text of the printing and typesetting industry... <span>#Trend Fashion</span></div>
							<div class="time-line">
								<p><span><i class="far fa-clock"></i>16 Mins ago</span></p>
								<p><span><i class="far fa-comments"></i>8 Comments</span></p>
							</div>
						</div>

					</div>
					<div class="item">
						
						<div class="images-blog"><img class="images-blogs" src="<?php echo $block->getViewFileUrl('images/blog2.jpg'); ?>" /></div>
						<div class="content">
							<div class="title">Lorem Ipsum is simply dummy text of the printing.</div>
							<div class="contents">Lorem Ipsum is simply dummy text of the printing and typesetting industry...<span>#Trend Fashion</span></div>
							<div class="time-line">
								<p><span><i class="far fa-clock"></i>16 Mins ago</span></p>
								<p><span><i class="far fa-comments"></i>8 Comments</span></p>
							</div>
						</div>

					</div>
					<div class="item">
						
						<div class="images-blog"><img class="images-blogs" src="<?php echo $block->getViewFileUrl('images/blog2.jpg'); ?>" /></div>
						<div class="content">
							<div class="title">Lorem Ipsum is simply dummy text of the printing.</div>
							<div class="contents">Lorem Ipsum is simply dummy text of the printing and typesetting industry...<span>#Trend Fashion</span></div>
							<div class="time-line">
								<p><span><i class="far fa-clock"></i>16 Mins ago</span></p>
								<p><span><i class="far fa-comments"></i>8 Comments</span></p>
							</div>
						</div>

					</div>

				</div>
			</div>


		</div>
	
</div>



<script>
	require(['jquery', 'owl'], function ($) {



		$('.owl-theme-blog').owlCarousel({
            // stagePadding: 50,
            loop:true,
            dots:false,
            margin:30,
            nav:true,
            autoplay: false,
            autoHeight: true,
            autoplayTimeout: 2000,
            smartSpeed: 800,
            responsive:{
            	0:{
            		items:1
            	},
            	600:{
            		items:2
            	},
            	1000:{
            		items:2
            	}
            }
        });
	});
</script>