<div class="category-list">
	<div class="container">
		<div class="row-s">
			<div class="col-md-4">
				<div class="wrapper">
					<div class="images"><img class="images" src="<?php echo $block->getViewFileUrl('images/category1.jpg'); ?>" />
					</div>
					<div class="content">			
						<h3>Categories</h3>
						<?php
						echo $this->getLayout()
						->createBlock('Magento\Cms\Block\Block')
						->setBlockId('women-category')
						->toHtml();
						?>
						<button class="btn-button">SHOW ALL</button>
					</div>
				</div>

			</div>
			<div class="col-md-4">
				<div class="wrapper">
					<div class="images"><img class="images" src="<?php echo $block->getViewFileUrl('images/category3.jpg'); ?>" />
					</div>
					<div class="content">			
						<h3>Categories</h3>
						<?php
						echo $this->getLayout()
						->createBlock('Magento\Cms\Block\Block')
						->setBlockId('gear-category')
						->toHtml();
						?>
						<button class="btn-button">SHOW ALL</button>
					</div>
				</div>

			</div>
			<div class="col-md-4">
				<div class="wrapper">
					<div class="images"><img class="images" src="<?php echo $block->getViewFileUrl('images/category2.jpg'); ?>" />
					</div>
					<div class="content">			
						<h3>Categories</h3>
						<?php
						echo $this->getLayout()
						->createBlock('Magento\Cms\Block\Block')
						->setBlockId('men-category')
						->toHtml();
						?>
						<button class="btn-button">SHOW ALL</button>
					</div>
				</div>

			</div>

			

		</div>
	</div>
</div>