<div class="category-list">
	<div class="container">
		<div class="row-s">
			<div class="col-md-4 col-sm-12">
				
				<div class="content">			
					<h3>Categories</h3>
					<p>WOMEN'S</p>
					<ul>

						<li><a href="#">Bags & Shoes</a></li>
						<li><a href="#">Dresses</a></li>
						<li><a href="#">Jewelry</a></li>
						<li><a href="#">Under Wear</a></li>
						<li><a href="#">Hair & Nail</a></li>
						<li><a href="#">Make Up</a></li>
					</ul>

					<button class="btn-button">SHOW ALL</button>
				</div>
				

			</div>
			<div class="col-md-4 col-sm-12">
				
				<div class="content">			
					<h3>Categories</h3>
					<p>MEN'S</p>
					<ul>
						<li><a href="#">Shirt</a></li>
						<li><a href="#">Trouser</a></li>
						<li><a href="#">Under Wear</a></li>
						<li><a href="#">Cym & Health</a></li>
						<li><a href="#">Glasses</a></li>
						<li><a href="#">Hair</a></li>
					</ul>

					<button class="btn-button">SHOW ALL</button>
				</div>
				

			</div>

			<div class="col-md-4 col-sm-12">
				
				<div class="content">			
					<h3>Categories</h3>
					<p>ACCESSORIES</p>
					<ul>
						<li><a href="#">Shoes & Boot</a></li>
						<li><a href="#">Hats & towel</a></li>
						<li><a href="#">Bags</a></li>
						<li><a href="#">Jewelry</a></li>
						<li><a href="#">Watches</a></li>
						<li><a href="#">Wallets</a></li>
					</ul>

					<button class="btn-button">SHOW ALL</button>
				</div>
				

			</div>

			

		</div>
	</div>
</div>