<div class="image-seller">
	<div class="row-s">
		<div class="col-md-6 col-sm-12"><img class="thumb-a" src="<?php echo $block->getViewFileUrl('images/s1.jpg'); ?>" />
		</div>
		<div class="col-md-3 col-sm-6"><img  class="thumb" src="<?php echo $block->getViewFileUrl('images/s4.jpg'); ?>" />
		</div>
		<div class="col-md-3 col-sm-6">
			<img class="anh-a" src="<?php echo $block->getViewFileUrl('images/s3.jpg'); ?>" />
			<img class="anh-b" src="<?php echo $block->getViewFileUrl('images/s2.jpg'); ?>" />
		</div>
		
	</div>
</div>