<div class="container image-seller">
	<div class="row-s">
		<div class="col-md-6"><img  src="<?php echo $block->getViewFileUrl('images/anhso1.jpg'); ?>" />
		</div>
		<div class="col-md-3"><img   src="<?php echo $block->getViewFileUrl('images/anhso2.jpg'); ?>" />
		</div>
		<div class="col-md-3">
			<img  src="<?php echo $block->getViewFileUrl('images/anhso3.jpg'); ?>" />
			<img   src="<?php echo $block->getViewFileUrl('images/anhso4.jpg'); ?>" />
		</div>
		
	</div>
</div>