<div id="owl-demo" class="owl-carousel owl-theme">
  <div class="item"><img class="images" src="<?php echo $block->getViewFileUrl('images/anh1.jpg'); ?>" /></div>
  <div class="item"><img class="images" src="<?php echo $block->getViewFileUrl('images/anh2.jpg'); ?>" /></div>
  <div class="item"><img class="images" src="<?php echo $block->getViewFileUrl('images/anh3.jpg'); ?>" /></div>
</div>

<script>

	require(['jquery','owl'], function ($) {


    $("#owl-demo").owlCarousel({
     
      navigation : true, // Show next and prev buttons
      slideSpeed : 300,
      paginationSpeed : 400,
      singleItem:true
      
      // "singleItem:true" is a shortcut for:
      // items : 1, 
      // itemsDesktop : false,
      // itemsDesktopSmall : false,
      // itemsTablet: false,
      // itemsMobile : false
      
    });



  });
</script>
