
<div class="special-item container">
	<div class="row-s">
		<div class="col-md-6 slide-1">
			<div class="title"><span class="titles">SPECIAL ITEMS</span></div>
			<?php
			echo $this->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('red')
			->toHtml();
			?>
		</div>
		<div class="col-md-6 slide-2">
			<div class="title"><span class="titles">MAY YOU LIKE</span></div>
			<?php
			echo $this->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('red')
			->toHtml();
			?>
		</div>
	</div>

</div>




<script>
	require(['jquery', 'slick'], function ($) {

		$('.special-item .product-items.widget-product-grid').addClass('regular slider');
		$(".regular").slick({
			dots: false,
			infinite: true,
			slidesToShow: 2,
			slidesToScroll: 2,

			rows:2,
			responsive: [
			{
				breakpoint: 1200,
				settings: {

					infinite: true,
					slidesToShow: 2,
					slidesToScroll: 2
				}
			},
			{
				breakpoint: 1141,
				settings: {

					
					dots: false,
					slidesToShow: 1,
					slidesToScroll: 1
				}
			},
			{
				breakpoint: 600,
				settings: {
					slidesToShow: 1,
					slidesToScroll: 1,
					dots: false,
				}
			},
			{
				breakpoint: 480,
				settings: {
					slidesToShow: 1,
					slidesToScroll: 1,
					dots: false,
				}
			}

			]
		});



	});
</script>