
<div class="seller-tab-one">
	<div class="row-s">
		<div class="col-md-12">

			<div class="main-contents">
				<div class="content-seller"><h3>2016</h3></div>
				<div class="move-center">
					<img class="images left" src="<?php echo $block->getViewFileUrl('images/left.png'); ?>" />
					<span>TRENDING</span>
					<img class="images right" src="<?php echo $block->getViewFileUrl('images/right.png'); ?>" />
				</div>
			</div>
			<hr/>

<!-- 			<div class="product data items"
			data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 500}, "active": 0, "disabledState": "disabled"}}'>
			<div class="item title" data-role="collapsible">
				<a class="switch" data-toggle="trigger" href="#tab-cars">BEST SELLER</a>
			</div>
			<div id="tab-cars" class="item content" data-role="content">        <?php
			// echo $this->getLayout()
			// ->createBlock('Magento\Cms\Block\Block')
			// ->setBlockId('red')
			// ->toHtml();
			?></div>

			<div class="item title" data-role="collapsible">
				<a class="switch" data-toggle="trigger" href="#tab-movies">ON SALE</a>
			</div>
			<div id="tab-movies" class="item content" data-role="content">
				
				<?php

				// $check=$this->getLayout()
				// ->createBlock('Magento\Cms\Block\Block')
				// ->setBlockId('red')
				// ->toHtml();
				// if(!$check)
				// {
				// 	echo "There is no Products";
				// }else{
				// 	echo $check;
				// }


				?>
			</div>

			<div class="item title" data-role="collapsible">
				<a class="switch" data-toggle="trigger" href="#tab-music">MOST VIEWED</a>
			</div>
			<div id="tab-music" class="item content" data-role="content">

				<?php 
				// echo $this->getLayout()
				// ->createBlock('Magento\Cms\Block\Block')
				// ->setBlockId('red')
				// ->toHtml();
				?>
			</div>
		</div> -->

		<div class="test-tab">
			<ul class="tabs">
				<li class="tab-link current" data-tab="tab-1">BEST SELLER</li>
				<li class="tab-link" data-tab="tab-2">ON SALE</li>
				<li class="tab-link" data-tab="tab-3">MOST VIEWED</li>

			</ul>

			<div id="tab-1" class="tab-content current">
				<?php 
				echo $this->getLayout()
				->createBlock('Magento\Cms\Block\Block')
				->setBlockId('red')
				->toHtml();
				?>
			</div>
			<div id="tab-2" class="tab-content">
				<?php 
				echo $this->getLayout()
				->createBlock('Magento\Cms\Block\Block')
				->setBlockId('red')
				->toHtml();
				?>
			</div>
			<div id="tab-3" class="tab-content">
				<?php 
				echo $this->getLayout()
				->createBlock('Magento\Cms\Block\Block')
				->setBlockId('red')
				->toHtml();
				?>
			</div>

		</div>
	</div>

</div>
</div>



<script>
	require(['jquery', 'owl'], function ($) {

		$('ul.tabs li').click(function(){
			var tab_id = $(this).attr('data-tab');

			$('ul.tabs li').removeClass('current');
			$('.tab-content').removeClass('current');

			$(this).addClass('current');
			$("#"+tab_id).addClass('current');
		});

		$('.seller-tab-one .product-items.widget-product-grid').addClass('owl-carousel owl-theme owl-themes');
		$('.seller-tab-one .product-item').addClass('item');

		$('.owl-themes').owlCarousel({
            // stagePadding: 50,
            loop:true,
            dots:false,
            margin:30,
            nav:true,
            autoplay: false,
            autoHeight: true,
            autoplayTimeout: 2000,
            smartSpeed: 800,
            responsive:{
            	0:{
            		items:1,
            		nav:false

            	},
            	480:{
            		items:1,
            		nav:false
            	},
            	640:{
            		items:3,
            		nav:false

            	},
            	1040:{
            		items:4,
            		nav:false,
            	},

            	1300:{
            		items:4,
            		nav:true,
            	}
            }
        });
	});
</script>