
<div class="container seller-tab-one">
	<div class="row-s">
		<div class="col-md-12">

			<div class="main-contents">
				<div class="content-seller"><h3>2016</h3></div>
				<div class="move-center">
					<img class="images left" src="<?php echo $block->getViewFileUrl('images/left.png'); ?>" />
					<span>TRENDING</span>
					<img class="images right" src="<?php echo $block->getViewFileUrl('images/right.png'); ?>" />
				</div>
			</div>
			<hr/>

			<div class="product data items"
			data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 500}, "active": 0, "disabledState": "disabled"}}'>
			<div class="item title" data-role="collapsible">
				<a class="switch" data-toggle="trigger" href="#tab-cars">BEST SELLER</a>
			</div>
			<div id="tab-cars" class="item content" data-role="content">        <?php
			echo $this->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('best-seller1')
			->toHtml();
			?></div>

			<div class="item title" data-role="collapsible">
				<a class="switch" data-toggle="trigger" href="#tab-movies">ON SALE</a>
			</div>
			<div id="tab-movies" class="item content" data-role="content">
				
				<?php

				$check=$this->getLayout()
				->createBlock('Magento\Cms\Block\Block')
				->setBlockId('best-seller2')
				->toHtml();
				if(!$check)
				{
					echo "There is no Products";
				}else{
					echo $check;
				}


				?>
			</div>

			<div class="item title" data-role="collapsible">
				<a class="switch" data-toggle="trigger" href="#tab-music">MOST VIEWED</a>
			</div>
			<div id="tab-music" class="item content" data-role="content">

				<?php 
				echo $this->getLayout()
				->createBlock('Magento\Cms\Block\Block')
				->setBlockId('best-seller1')
				->toHtml();
				?>
			</div>
		</div>
	</div>

</div>
</div>



<script>
	require(['jquery', 'owl'], function ($) {

		$('.seller-tab-one .product-items.widget-product-grid').addClass('owl-carousel owl-theme owl-themes');
		$('.seller-tab-one .product-item').addClass('item');

		$('.owl-themes').owlCarousel({
            // stagePadding: 50,
            loop:true,
            dots:false,
            margin:30,
            nav:true,
            autoplay: false,
            autoHeight: true,
            autoplayTimeout: 2000,
            smartSpeed: 800,
            responsive:{
            	0:{
            		items:1
            	},
            	600:{
            		items:2
            	},
            	1000:{
            		items:3
            	}
            }
        });
	});
</script>